CREATE DATABASE IF NOT EXISTS dr_test;

USE dr_test;

CREATE TABLE Persons(
	id INT(8) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(30) NOT NULL,
    first_surname VARCHAR(30) NOT NULL,
    second_surname VARCHAR(30),
    type ENUM('VISITOR','EMPLOYEE') DEFAULT 'VISITOR',
    picture VARCHAR(100)
);

CREATE TABLE Visits(
	id INT(8) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    reason VARCHAR(50) NOT NULL,
    person_id INT(8) NOT NULL,
	FOREIGN KEY (person_id) REFERENCES Persons(id) ON UPDATE CASCADE ON DELETE RESTRICT
);


SELECT * FROM Persons;
SELECT * FROM Visits;
